In [1]:
from numpy import array,zeros,diag
from numpy import dot
from scipy.linalg import svd

In [2]:
A=array([[1,2],[3,4],[5,6]])
print('Original matrix \n',A)
print()
U,S,Vt=svd(A)
print(U)
print()
print(S)
print()
print(Vt)
print()


Original matrix 
 [[1 2]
 [3 4]
 [5 6]]

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

[9.52551809 0.51430058]

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]



In [3]:
#For creating Identity matrix
Sigma=zeros((A.shape[0],A.shape[1]))
print(Sigma)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
Sigma[:A.shape[1],:A.shape[1]]=diag(S)
print(diag(S))

[[9.52551809 0.        ]
 [0.         0.51430058]]


In [5]:
A_recons=U.dot(Sigma.dot(Vt))
print('reconstructed matrix: \n',A_recons)

reconstructed matrix: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
